import type { Comment, Group, Place, Post, Product, Review } from "./schema";

export const PILOT_CITY = "São Paulo";
export const PILOT_CITY_CENTER = { lat: -23.5614, lng: -46.6559 };

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 3600 * 1000).toISOString();
}

function daysAgo(days: number): string {
  return hoursAgo(days * 24);
}

export const seedPlaces: Place[] = [
  {
    id: "place-figueiras",
    name: "Parque Municipal das Figueiras",
    category: "parque",
    address: "Rua das Acácias, 500",
    neighborhood: "Pinheiros",
    city: PILOT_CITY,
    lat: -23.5671,
    lng: -46.6935,
    attributes: ["aceita_caes", "area_cercada", "agua_disponivel", "sombra"],
    priceLevel: 0,
    verified: true,
    openNow: true,
    seeded: true,
  },
  {
    id: "place-lago-verde",
    name: "Praça do Lago Verde",
    category: "parque",
    address: "Avenida das Palmeiras, 120",
    neighborhood: "Vila Madalena",
    city: PILOT_CITY,
    lat: -23.5538,
    lng: -46.6908,
    attributes: ["aceita_caes", "sombra", "agua_disponivel"],
    priceLevel: 0,
    verified: false,
    openNow: true,
    seeded: true,
  },
  {
    id: "place-aurora",
    name: "Café Bistrô Aurora",
    category: "restaurante",
    address: "Rua Harmonia, 245",
    neighborhood: "Vila Madalena",
    city: PILOT_CITY,
    lat: -23.5545,
    lng: -46.6882,
    attributes: ["area_externa", "agua_disponivel", "aceita_raca_grande"],
    priceLevel: 2,
    verified: true,
    openNow: true,
    seeded: true,
  },
  {
    id: "place-bistro-bairro",
    name: "Bistrô do Bairro",
    category: "restaurante",
    address: "Rua Girassol, 88",
    neighborhood: "Vila Madalena",
    city: PILOT_CITY,
    lat: -23.5561,
    lng: -46.6857,
    attributes: ["area_externa", "ruido_alto"],
    priceLevel: 2,
    verified: false,
    openNow: true,
    seeded: true,
  },
  {
    id: "place-pao-patas",
    name: "Padaria Pão & Patas",
    category: "restaurante",
    address: "Rua dos Pinheiros, 1200",
    neighborhood: "Pinheiros",
    city: PILOT_CITY,
    lat: -23.5647,
    lng: -46.6899,
    attributes: ["area_externa", "agua_disponivel", "equipe_paciente"],
    priceLevel: 1,
    verified: true,
    openNow: true,
    seeded: true,
  },
  {
    id: "place-bicho-bem",
    name: "Clínica Bicho Bem",
    category: "veterinario",
    address: "Rua Teodoro Sampaio, 900",
    neighborhood: "Pinheiros",
    city: PILOT_CITY,
    lat: -23.5592,
    lng: -46.6919,
    attributes: ["emergencia_24h", "equipe_paciente", "aceita_raca_grande"],
    priceLevel: 3,
    verified: true,
    openNow: true,
    seeded: true,
  },
  {
    id: "place-vet-amigo",
    name: "Vet Amigo 24 horas",
    category: "veterinario",
    address: "Avenida Rebouças, 1500",
    neighborhood: "Jardins",
    city: PILOT_CITY,
    lat: -23.5628,
    lng: -46.6712,
    attributes: ["emergencia_24h", "aceita_raca_grande"],
    priceLevel: 3,
    verified: true,
    openNow: true,
    seeded: true,
  },
  {
    id: "place-banho-cia",
    name: "Banho & Cia Pet",
    category: "banho_tosa",
    address: "Rua Fradique Coutinho, 300",
    neighborhood: "Pinheiros",
    city: PILOT_CITY,
    lat: -23.5608,
    lng: -46.6866,
    attributes: ["equipe_paciente", "aceita_raca_grande"],
    priceLevel: 2,
    verified: false,
    openNow: false,
    seeded: true,
  },
  {
    id: "place-pelo-macio",
    name: "Estúdio Pelo Macio",
    category: "banho_tosa",
    address: "Rua Harmonia, 60",
    neighborhood: "Vila Madalena",
    city: PILOT_CITY,
    lat: -23.5529,
    lng: -46.6875,
    attributes: ["equipe_paciente", "ruido_alto"],
    priceLevel: 2,
    verified: false,
    openNow: true,
    seeded: true,
  },
  {
    id: "place-recanto",
    name: "Hotel Recanto dos Pets",
    category: "hospedagem",
    address: "Estrada do Morumbi, 2000",
    neighborhood: "Morumbi",
    city: PILOT_CITY,
    lat: -23.6021,
    lng: -46.7104,
    attributes: ["portoes_fechados", "area_cercada", "aceita_raca_grande"],
    priceLevel: 3,
    verified: true,
    openNow: true,
    seeded: true,
  },
  {
    id: "place-caminho-certo",
    name: "Caminho Certo Passeios",
    category: "passeador_adestrador",
    address: "Rua Cardeal Arcoverde, 700",
    neighborhood: "Pinheiros",
    city: PILOT_CITY,
    lat: -23.5621,
    lng: -46.6903,
    attributes: ["equipe_paciente"],
    priceLevel: 2,
    verified: false,
    openNow: true,
    seeded: true,
  },
  {
    id: "place-adestra-bem",
    name: "Adestra Bem",
    category: "passeador_adestrador",
    address: "Rua Clélia, 400",
    neighborhood: "Lapa",
    city: PILOT_CITY,
    lat: -23.5262,
    lng: -46.7048,
    attributes: ["equipe_paciente", "aceita_raca_grande"],
    priceLevel: 2,
    verified: true,
    openNow: true,
    seeded: true,
  },
];

export const seedReviews: Review[] = [
  {
    id: "review-figueiras-1",
    placeId: "place-figueiras",
    authorName: "Ana Cláudia",
    criteria: ["aceita_raca_grande", "area_cercada", "sombra"],
    rating: 5,
    text: "Área cercada de verdade, consegui soltar a Nina sem preocupação.",
    createdAt: daysAgo(9),
  },
  {
    id: "review-figueiras-2",
    placeId: "place-figueiras",
    authorName: "Rodrigo",
    criteria: ["area_cercada", "agua_disponivel"],
    rating: 4,
    text: "Bebedouro funcionando e bastante sombra no fim da tarde.",
    createdAt: daysAgo(21),
  },
  {
    id: "review-aurora-1",
    placeId: "place-aurora",
    authorName: "Marina Lopes",
    criteria: ["area_externa", "aceita_raca_grande", "equipe_paciente"],
    rating: 5,
    text: "Trouxeram água para o Thor sem eu pedir. Mesas externas bem espaçadas.",
    createdAt: daysAgo(4),
  },
  {
    id: "review-aurora-2",
    placeId: "place-aurora",
    authorName: "Pedro",
    criteria: ["area_externa", "agua_disponivel"],
    rating: 4,
    text: "Bom para o café da manhã, mas fica cheio nos fins de semana.",
    createdAt: daysAgo(12),
  },
  {
    id: "review-bistro-1",
    placeId: "place-bistro-bairro",
    authorName: "Camila",
    criteria: ["ruido_alto"],
    rating: 3,
    text: "Comida boa, mas o barulho da rua assustou meu pet.",
    createdAt: daysAgo(6),
  },
  {
    id: "review-bicho-bem-1",
    placeId: "place-bicho-bem",
    authorName: "Joana Ribeiro",
    criteria: ["emergencia_24h", "equipe_paciente", "aceita_raca_grande"],
    rating: 5,
    text: "Atenderam de madrugada. Equipe explicou cada passo com calma.",
    createdAt: daysAgo(2),
  },
  {
    id: "review-bicho-bem-2",
    placeId: "place-bicho-bem",
    authorName: "Thiago",
    criteria: ["equipe_paciente"],
    rating: 4,
    text: "Espera um pouco longa, mas o atendimento foi cuidadoso.",
    createdAt: daysAgo(17),
  },
  {
    id: "review-banho-cia-1",
    placeId: "place-banho-cia",
    authorName: "Letícia",
    criteria: ["equipe_paciente"],
    rating: 4,
    text: "Paciência com meu gato, que odeia banho.",
    createdAt: daysAgo(11),
  },
  {
    id: "review-pelo-macio-1",
    placeId: "place-pelo-macio",
    authorName: "Bruno",
    criteria: ["ruido_alto", "equipe_paciente"],
    rating: 3,
    text: "Secador muito barulhento, mas o resultado ficou ótimo.",
    createdAt: daysAgo(8),
  },
  {
    id: "review-recanto-1",
    placeId: "place-recanto",
    authorName: "Fernanda",
    criteria: ["portoes_fechados", "area_cercada"],
    rating: 5,
    text: "Fiquei tranquila na viagem: portões fechados e área grande.",
    createdAt: daysAgo(30),
  },
];

export const seedGroups: Group[] = [
  {
    id: "group-caes-sp",
    name: "Cães de São Paulo",
    kind: "especie",
    description: "Rotina, passeios e cuidados com cães na cidade.",
    members: 1240,
    city: PILOT_CITY,
  },
  {
    id: "group-golden",
    name: "Golden Retriever Brasil",
    kind: "raca",
    description: "Tutores de golden trocando dicas de pelagem e articulação.",
    members: 486,
    city: null,
  },
  {
    id: "group-pinheiros",
    name: "Tutores de Pinheiros",
    kind: "cidade",
    description: "Encontros de bairro e lugares que aceitam pets.",
    members: 213,
    city: PILOT_CITY,
  },
  {
    id: "group-adestramento",
    name: "Adestramento positivo",
    kind: "interesse",
    description:
      "Reforço positivo sem punição, com apoio de quem já viveu isso.",
    members: 908,
    city: null,
  },
  {
    id: "group-corridas",
    name: "Corridas com pets",
    kind: "atividade",
    description: "Treinos leves, hidratação e cuidados com piso quente.",
    members: 154,
    city: PILOT_CITY,
  },
];

export const seedProducts: Product[] = [
  {
    id: "product-racao-adulto",
    name: "Ração Adulto Porte Médio",
    brand: "NutriPet",
    category: "alimentacao",
    description:
      "Formulação para manutenção de peso em cães adultos de 10 a 25 kg.",
    priceBRL: 189.9,
    partnerName: "Agro Pet Pinheiros",
    partnerPlaceId: "place-pao-patas",
    sizes: ["medio", "pequeno"],
    lifeStages: ["adulto"],
    species: ["cao"],
    routineTags: ["alimentacao"],
    link: "https://example.com/parceiros/nutripet-racao-adulto",
  },
  {
    id: "product-racao-idoso",
    name: "Ração Sênior Articulações",
    brand: "NutriPet",
    category: "alimentacao",
    description: "Com condroitina e glucosamina para cães acima de 7 anos.",
    priceBRL: 224.5,
    partnerName: "Agro Pet Pinheiros",
    partnerPlaceId: "place-pao-patas",
    sizes: ["medio", "grande", "gigante"],
    lifeStages: ["idoso"],
    species: ["cao"],
    routineTags: ["alimentacao"],
    link: "https://example.com/parceiros/nutripet-racao-senior",
  },
  {
    id: "product-shampoo",
    name: "Shampoo Hipoalergênico Neutro",
    brand: "Pelo Macio",
    category: "higiene",
    description: "Indicado para pele sensível e banhos frequentes.",
    priceBRL: 54.9,
    partnerName: "Estúdio Pelo Macio",
    partnerPlaceId: "place-pelo-macio",
    sizes: ["mini", "pequeno", "medio", "grande", "gigante"],
    lifeStages: ["filhote", "adulto", "idoso"],
    species: ["cao", "gato"],
    routineTags: ["higiene"],
    link: "https://example.com/parceiros/pelo-macio-shampoo",
  },
  {
    id: "product-peitoral",
    name: "Peitoral Anti-puxão",
    brand: "Caminho Certo",
    category: "passeio",
    description:
      "Distribui a força no tórax e reduz o puxão durante o passeio.",
    priceBRL: 139.0,
    partnerName: "Caminho Certo Passeios",
    partnerPlaceId: "place-caminho-certo",
    sizes: ["medio", "grande", "gigante"],
    lifeStages: ["adulto", "idoso"],
    species: ["cao"],
    routineTags: ["passeio", "socializacao"],
    link: "https://example.com/parceiros/caminho-certo-peitoral",
  },
  {
    id: "product-antipulgas",
    name: "Antipulgas e Carrapatos Mensal",
    brand: "Vet Amigo",
    category: "saude",
    description: "Proteção mensal conforme orientação do veterinário.",
    priceBRL: 98.0,
    partnerName: "Vet Amigo 24 horas",
    partnerPlaceId: "place-vet-amigo",
    sizes: ["pequeno", "medio", "grande"],
    lifeStages: ["adulto", "idoso"],
    species: ["cao", "gato"],
    routineTags: ["higiene"],
    link: "https://example.com/parceiros/vet-amigo-antipulgas",
  },
  {
    id: "product-condroitina",
    name: "Suplemento Condroitina",
    brand: "Vet Amigo",
    category: "saude",
    description: "Apoio à mobilidade em pets idosos ou de porte grande.",
    priceBRL: 132.0,
    partnerName: "Vet Amigo 24 horas",
    partnerPlaceId: "place-vet-amigo",
    sizes: ["grande", "gigante", "medio"],
    lifeStages: ["idoso"],
    species: ["cao"],
    routineTags: ["alimentacao"],
    link: "https://example.com/parceiros/vet-amigo-condroitina",
  },
  {
    id: "product-mordedor",
    name: "Mordedor de Borracha Resistente",
    brand: "BrincaPet",
    category: "enriquecimento",
    description: "Para pets que precisam gastar energia em casa.",
    priceBRL: 42.9,
    partnerName: "Agro Pet Pinheiros",
    partnerPlaceId: "place-pao-patas",
    sizes: ["medio", "grande", "gigante"],
    lifeStages: ["filhote", "adulto"],
    species: ["cao"],
    routineTags: ["enriquecimento"],
    link: "https://example.com/parceiros/brincapet-mordedor",
  },
  {
    id: "product-tapete-farejar",
    name: "Tapete de Farejar",
    brand: "BrincaPet",
    category: "enriquecimento",
    description: "Estimula o olfato e ajuda a acalmar em dias de chuva.",
    priceBRL: 79.9,
    partnerName: "Agro Pet Pinheiros",
    partnerPlaceId: "place-pao-patas",
    sizes: ["mini", "pequeno", "medio"],
    lifeStages: ["filhote", "adulto", "idoso"],
    species: ["cao", "gato"],
    routineTags: ["enriquecimento"],
    link: "https://example.com/parceiros/brincapet-tapete",
  },
  {
    id: "product-fonte-agua",
    name: "Fonte de Água Circulante",
    brand: "Água Viva",
    category: "saude",
    description: "Estimula a hidratação, especialmente em gatos.",
    priceBRL: 169.0,
    partnerName: "Clínica Bicho Bem",
    partnerPlaceId: "place-bicho-bem",
    sizes: ["mini", "pequeno", "medio"],
    lifeStages: ["filhote", "adulto", "idoso"],
    species: ["gato", "cao"],
    routineTags: ["alimentacao", "higiene"],
    link: "https://example.com/parceiros/agua-viva-fonte",
  },
  {
    id: "product-escova",
    name: "Escova Removedora de Pelos",
    brand: "Pelo Macio",
    category: "higiene",
    description: "Reduz pelos soltos em casa e ajuda na troca de pelagem.",
    priceBRL: 62.9,
    partnerName: "Estúdio Pelo Macio",
    partnerPlaceId: "place-pelo-macio",
    sizes: ["pequeno", "medio", "grande", "gigante"],
    lifeStages: ["adulto", "idoso"],
    species: ["cao", "gato"],
    routineTags: ["higiene"],
    link: "https://example.com/parceiros/pelo-macio-escova",
  },
];

export const seedPosts: Post[] = [
  {
    id: "post-vet-madrugada",
    authorName: "Ana Cláudia",
    authorId: "seed-ana",
    petName: "Nina",
    type: "pergunta",
    groupId: "group-caes-sp",
    title: "Veterinário de madrugada perto de Pinheiros?",
    body: "A Nina começou com vômito às 23h. Alguém tem indicação de plantão 24h que atenda bem cães grandes?",
    city: PILOT_CITY,
    createdAt: hoursAgo(5),
    helpfulCount: 3,
    reported: false,
    hidden: false,
  },
  {
    id: "post-figueiras",
    authorName: "Rodrigo",
    authorId: "seed-rodrigo",
    petName: "Thor",
    type: "recomendacao",
    groupId: "group-pinheiros",
    title: "Parque das Figueiras tem área cercada de verdade",
    body: "Fui cedo no sábado e a área cercada estava limpa. Bebedouro funcionando e sombra na maior parte do gramado.",
    city: PILOT_CITY,
    createdAt: hoursAgo(28),
    helpfulCount: 7,
    reported: false,
    hidden: false,
  },
  {
    id: "post-perdido-mel",
    authorName: "Camila",
    authorId: "seed-camila",
    petName: "Mel",
    type: "perdido_encontrado",
    groupId: "group-pinheiros",
    title: "Mel se perdeu na Vila Madalena",
    body: "Ela escapou pelo portão na Rua Harmonia. Usa coleira azul e é arisca com estranhos. Se vir, chame sem correr.",
    city: PILOT_CITY,
    createdAt: hoursAgo(10),
    helpfulCount: 12,
    reported: false,
    hidden: false,
  },
  {
    id: "post-feira-adocao",
    authorName: "Tutores de Pinheiros",
    authorId: "seed-grupo-pinheiros",
    petName: null,
    type: "evento",
    groupId: "group-pinheiros",
    title: "Feira de adoção no domingo, 10h",
    body: "Praça do Lago Verde, com apoio de dois veterinários voluntários. Leve seus pets para socializar.",
    city: PILOT_CITY,
    createdAt: daysAgo(2),
    helpfulCount: 9,
    reported: false,
    hidden: false,
  },
  {
    id: "post-piso-quente",
    authorName: "Joana Ribeiro",
    authorId: "seed-joana",
    petName: "Bento",
    type: "dica",
    groupId: "group-corridas",
    title: "Teste do dorso da mão antes do passeio",
    body: "Se o asfalto estiver quente para a sua mão, estará quente para as patas. Nosso grupo corre só antes das 8h.",
    city: PILOT_CITY,
    createdAt: daysAgo(3),
    helpfulCount: 15,
    reported: false,
    hidden: false,
  },
  {
    id: "post-pelagem-golden",
    authorName: "Fernanda",
    authorId: "seed-fernanda",
    petName: "Simba",
    type: "pergunta",
    groupId: "group-golden",
    title: "Troca de pelagem está intensa. Alguma dica?",
    body: "Escovo todos os dias e ainda encontro pelo em tudo. Vale usar ração específica?",
    city: null,
    createdAt: daysAgo(4),
    helpfulCount: 4,
    reported: false,
    hidden: false,
  },
];

export const seedComments: Comment[] = [
  {
    id: "comment-vet-1",
    postId: "post-vet-madrugada",
    authorName: "Thiago",
    authorId: "seed-thiago",
    body: "Clínica Bicho Bem atende 24h na Teodoro Sampaio. Levei de madrugada e resolveram rápido.",
    helpful: true,
    reported: false,
    createdAt: hoursAgo(4),
  },
  {
    id: "comment-vet-2",
    postId: "post-vet-madrugada",
    authorName: "Ana Cláudia",
    authorId: "seed-ana",
    body: "Obrigada! Estamos indo para lá agora.",
    helpful: false,
    reported: false,
    createdAt: hoursAgo(3),
  },
  {
    id: "comment-figueiras-1",
    postId: "post-figueiras",
    authorName: "Marina Lopes",
    authorId: "seed-marina",
    body: "Confirmo. Só cuidado com o setor perto do portão principal, tem muito estacionamento.",
    helpful: true,
    reported: false,
    createdAt: hoursAgo(20),
  },
  {
    id: "comment-perdido-1",
    postId: "post-perdido-mel",
    authorName: "Bruno",
    authorId: "seed-bruno",
    body: "Vi uma cadela parecida perto da Fradique às 7h. Vou mandar foto no seu contato.",
    helpful: true,
    reported: false,
    createdAt: hoursAgo(8),
  },
  {
    id: "comment-perdido-2",
    postId: "post-perdido-mel",
    authorName: "Letícia",
    authorId: "seed-leticia",
    body: "Ative o modo perdido na carteirinha dela. Quem achar consegue ver o contato pelo QR.",
    helpful: true,
    reported: false,
    createdAt: hoursAgo(7),
  },
  {
    id: "comment-pelagem-1",
    postId: "post-pelagem-golden",
    authorName: "Pedro",
    authorId: "seed-pedro",
    body: "Aqui ajudou escovar com removedor a cada dois dias e manter a ração com ômega 3.",
    helpful: true,
    reported: false,
    createdAt: daysAgo(3),
  },
];
